name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker image tag
        run: |
          echo "repo_name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "tag=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.repo_name }}:${{ env.tag }} .
          docker tag ghcr.io/${{ env.repo_name }}:${{ env.tag }} ghcr.io/${{ env.repo_name }}:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.repo_name }}:${{ env.tag }}
          docker push ghcr.io/${{ env.repo_name }}:latest